version:  '3.9'
services:
  backend:
    image: 'sschonss/backend-dev-project'
    ports:
      - '80:8000'
    networks:
      - dev-net
#  mysql:
#    image: 'mysql/mysql-server:8.0'
#    ports:
#      - '3306:3306'
#    environment:
#      MYSQL_ROOT_PASSWORD: 'password'
#      MYSQL_ROOT_HOST: '%'
#      MYSQL_DATABASE: 'laravel'
#      MYSQL_USER: 'sail'
#      MYSQL_PASSWORD: 'password'
#      MYSQL_ALLOW_EMPTY_PASSWORD: 1
#    volumes:
#      - 'dev-net-mysql:/var/lib/mysql'
#    networks:
#      - dev-net
  frontend:
    image: 'sschonss/frontend-dev-project'
    ports:
      - '4200:4200'
    networks:
        - dev-net
networks:
  dev-net:
    driver: bridge
