services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
        command: sh -c "composer install && php artisan key:generate && php artisan serve --host 0.0.0.0 --port 8000"
        depends_on:
            - mysql
        networks:
            - dev-project
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'laravel'
            MYSQL_USER: 'sail'
            MYSQL_PASSWORD: 'password'
        volumes:
            - 'dev-project-mysql:/var/lib/mysql'
        networks:
            - dev-project
networks:
    dev-project:
        driver: bridge
volumes:
    dev-project-mysql:
        driver: local
